In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
books = pd.read_csv('Books.csv')
ratings = pd.read_csv('Ratings.csv')
users = pd.read_csv('Users.csv')

C:\Users\panch\AppData\Local\Temp\ipykernel_18060\378180666.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [7]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [8]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [9]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [14]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [15]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [16]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [17]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [18]:
books.duplicated().sum()

0

In [19]:
users.duplicated().sum()

0

In [20]:
ratings.duplicated().sum()

0

## Popularity based Recommendation System

In [25]:
ratings_with_names = ratings.merge(books, on= "ISBN")

In [33]:
no_ratings_df = ratings_with_names.groupby('Book-Title').count()['Book-Rating'].reset_index()
no_ratings_df.rename(columns= {'Book-Rating': 'no_ratings'},inplace = True)
no_ratings_df

                                               Book-Title  no_ratings
0        A Light in the Storm: The Civil War Diary of ...           4
1                                   Always Have Popsicles           1
2                    Apple Magic (The Collector's series)           1
3        Ask Lily (Young Women of Faith: Lily Series, ...           1
4        Beyond IBM: Leadership Marketing and Finance ...           1
...                                                   ...         ...
241066                                      Ãƒ?Ã‚?lpiraten.           2
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.           4
241068                                Ãƒ?Ã‚?sterlich leben.           1
241069                              Ãƒ?Ã‚?stlich der Berge.           3
241070                                  Ãƒ?Ã‚?thique en toc           2

[241071 rows x 2 columns]

In [47]:
# avg_ratings_df = ratings_with_names.groupby('Book-Title').mean()['Book-Rating'].reset_index()
# # avg_ratings_df.rename(columns= {'Book-Rating': 'average_ratings'},inplace = True)
# # avg_ratings_df

In [42]:
# ratings_with_names["Book-Rating"] = ratings_with_names["Book-Rating"].astype('float')

In [43]:
# ratings_with_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1031136 entries, 0 to 1031135
Data columns (total 10 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   User-ID              1031136 non-null  int64
 1   ISBN                 1031136 non-null  object
 2   Book-Rating          1031136 non-null  float64
 3   Book-Title           1031136 non-null  object
 4   Book-Author          1031134 non-null  object
 5   Year-Of-Publication  1031136 non-null  object
 6   Publisher            1031134 non-null  object
 7   Image-URL-S          1031136 non-null  object
 8   Image-URL-M          1031136 non-null  object
 9   Image-URL-L          1031132 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 78.7+ MB

In [46]:
avg_ratings_df = ratings_with_names.groupby('Book-Title').mean(numeric_only = True)['Book-Rating'].reset_index()
avg_ratings_df.rename(columns= {'Book-Rating': 'average_ratings'},inplace = True)
avg_ratings_df

                                               Book-Title  average_ratings
0        A Light in the Storm: The Civil War Diary of ...         2.250000
1                                   Always Have Popsicles         0.000000
2                    Apple Magic (The Collector's series)         0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...         8.000000
4        Beyond IBM: Leadership Marketing and Finance ...         0.000000
...                                                   ...              ...
241066                                      Ãƒ?Ã‚?lpiraten.         0.000000
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.         5.250000
241068                                Ãƒ?Ã‚?sterlich leben.         7.000000
241069                              Ãƒ?Ã‚?stlich der Berge.         2.666667
241070                                  Ãƒ?Ã‚?thique en toc         4.000000

[241071 rows x 2 columns]

In [49]:
popular_df= no_ratings_df.merge(avg_ratings_df, on = "Book-Title")
popular_df

,Book-Title,no_ratings,average_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ãƒ?Ã‚?lpiraten.,2,0.000000
241067,Ãƒ?Ã‚?rger mit Produkt X. Roman.,4,5.250000
241068,Ãƒ?Ã‚?sterlich leben.,1,7.000000
241069,Ãƒ?Ã‚?stlich der Berge.,3,2.666667
241070,Ãƒ?Ã‚?thique en toc,2,4.000000

In [54]:
#sort the values with no of ratings above 250, and filter out 50 books with highest avg rating
popular_df = popular_df[popular_df['no_ratings']>=250].sort_values('average_ratings',ascending = False).head(50)
popular_df

,Book-Title,no_ratings,average_ratings
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
196326,The Lovely Bones: A Novel,1295,4.468726
206502,The Secret Life of Bees,774,4.447028
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
74750,Girl with a Pearl Earring,526,4.218631
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
107962,Life of Pi,664,4.088855
76343,Good in Bed,490,4.055102
170101,Suzanne's Diary for Nicholas,457,3.820569
219349,Timeline,552,3.750000
14392,Angels &amp; Demons,670,3.708955
202550,The Poisonwood Bible: A Novel,494,3.609312
202244,The Pilot's Wife : A Novel,568,3.593310
818,1st to Die: A Novel,509,3.575639
159301,She's Come Undone (Oprah's Book Club),468,3.570513
200253,The Notebook,650,3.560000
93210,Interview with the Vampire,508,3.551181
199237,The Nanny Diaries: A Novel,828,3.530193
27922,Bridget Jones's Diary,815,3.527607
52983,Divine Secrets of the Ya-Ya Sisterhood: A Novel,740,3.437838
209298,The Summons,655,3.432061
97767,Jurassic Park,488,3.428279
169201,Summer Sisters,573,3.361257
201472,The Partner,478,3.290795
162651,Snow Falling on Cedars,662,3.252266
5303,A Painted House,838,3.231504
55358,Dreamcatcher,481,3.212058
210064,The Testament,617,3.179903
189266,The Girls' Guide to Hunting and Fishing,573,3.139616
6980,A Time to Kill,549,3.122040
181392,The Client,483,3.084886
187702,The Firm,569,3.080844
193428,The Joy Luck Club,555,3.055856
193881,The King of Torts,458,3.039301
85957,House of Sand and Fog,588,3.030612
180737,The Chamber,509,3.015717
204153,The Reader,466,3.012876
204000,The Rainmaker,501,2.922156
205523,The Runaway Jury,520,2.880769
209117,The Street Lawyer,545,2.851376
179274,The Brethren,556,2.850719
119580,Message in a Bottle,496,2.778226
79829,Hannibal,468,2.760684
191824,The Horse Whisperer,507,2.686391
201692,The Pelican Brief,581,2.611015
234951,Wild Animus,2502,1.019584

In [62]:
popular_df = popular_df.merge(books, on = "Book-Title").drop_duplicates('Book-Title')[["Book-Title","Book-Author","Image-URL-M","no_ratings", "average_ratings"]]

In [63]:
popular_df

,Book-Title,Book-Author,Image-URL-M,no_ratings,average_ratings
0,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
3,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
5,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
13,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
19,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
20,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
26,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
29,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
30,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
31,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
32,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
36,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
38,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
42,Timeline,MICHAEL CRICHTON,http://images.amazon.com/images/P/0345417623.0...,552,3.750000
49,Angels &amp; Demons,Dan Brown,http://images.amazon.com/images/P/0671027360.0...,670,3.708955
54,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,494,3.609312
55,The Pilot's Wife : A Novel,Anita Shreve,http://images.amazon.com/images/P/0316601950.0...,568,3.593310
56,1st to Die: A Novel,James Patterson,http://images.amazon.com/images/P/0446610038.0...,509,3.575639
58,She's Come Undone (Oprah's Book Club),Wally Lamb,http://images.amazon.com/images/P/0671021001.0...,468,3.570513
59,The Notebook,Nicholas Sparks,http://images.amazon.com/images/P/0446605239.0...,650,3.560000
64,Interview with the Vampire,Anne Rice,http://images.amazon.com/images/P/0345337662.0...,508,3.551181
66,The Nanny Diaries: A Novel,Emma McLaughlin,http://images.amazon.com/images/P/0312278586.0...,828,3.530193
68,Bridget Jones's Diary,Helen Fielding,http://images.amazon.com/images/P/0330332775.0...,815,3.527607
74,Divine Secrets of the Ya-Ya Sisterhood: A Novel,Rebecca Wells,http://images.amazon.com/images/P/0060928336.0...,740,3.437838
77,The Summons,John Grisham,http://images.amazon.com/images/P/0440241073.0...,655,3.432061
81,Jurassic Park,Michael Crichton,http://images.amazon.com/images/P/0345370775.0...,488,3.428279
88,Summer Sisters,Judy Blume,http://images.amazon.com/images/P/0385324057.0...,573,3.361257
92,The Partner,John Grisham,http://images.amazon.com/images/P/0385472951.0...,478,3.290795
96,Snow Falling on Cedars,David Guterson,http://images.amazon.com/images/P/0151001006.0...,662,3.252266
103,A Painted House,John Grisham,http://images.amazon.com/images/P/044023722X.0...,838,3.231504
108,Dreamcatcher,Stephen King,http://images.amazon.com/images/P/0743211383.0...,481,3.212058
120,The Testament,John Grisham,http://images.amazon.com/images/P/0440234743.0...,617,3.179903
127,The Girls' Guide to Hunting and Fishing,Melissa Bank,http://images.amazon.com/images/P/0140293248.0...,573,3.139616
131,A Time to Kill,JOHN GRISHAM,http://images.amazon.com/images/P/0440211727.0...,549,3.122040
138,The Client,John Grisham,http://images.amazon.com/images/P/038542471X.0...,483,3.084886
142,The Firm,John Grisham,http://images.amazon.com/images/P/0385416342.0...,569,3.080844
149,The Joy Luck Club,Amy Tan,http://images.amazon.com/images/P/0804106304.0...,555,3.055856
152,The King of Torts,John Grisham,http://images.amazon.com/images/P/0385508042.0...,458,3.039301
156,House of Sand and Fog,Andre Dubus III,http://images.amazon.com/images/P/0375727345.0...,588,3.030612
158,The Chamber,John Grisham,http://images.amazon.com/images/P/0385424728.0...,509,3.015717
163,The Reader,Bernhard Schlink,http://images.amazon.com/images/P/0679442790.0...,466,3.012876
168,The Rainmaker,JOHN GRISHAM,http://images.amazon.com/images/P/044022165X.0...,501,2.922156
175,The Runaway Jury,JOHN GRISHAM,http://images.amazon.com/images/P/0440221471.0...,520,2.880769
181,The Street Lawyer,JOHN GRISHAM,http://images.amazon.com/images/P/0440225701.0...,545,2.851376
186,The Brethren,JOHN GRISHAM,http://images.amazon.com/images/P/0385497466.0...,556,2.850719
191,Message in a Bottle,Nicholas Sparks,http://images.amazon.com/images/P/0446523569.0...,496,2.778226
196,Hannibal,Thomas Harris,http://images.amazon.com/images/P/0440224675.0...,468,2.760684
208,The Horse Whisperer,Nicholas Evans,http://images.amazon.com/images/P/0440222656.0...,507,2.686391
212,The Pelican Brief,John Grisham,http://images.amazon.com/images/P/0440214041.0...,581,2.611015
215,Wild Animus,Rich Shapero,http://images.amazon.com/images/P/0971880107.0...,2502,1.019584

## Collabarative filtering base recommendation system

In [75]:
x = ratings_with_names.groupby('User-ID').count()['Book-Rating']>200
top_readers = x[x].index
top_readers

Index([   254,   2276,   2766,   2977,   3363,   4017,   4385,   6251,   6323,
         6543,
       ...
       271705, 273979, 274004, 274061, 274301, 274308, 275970, 277427, 277639,
       278418],
      dtype='int64', name='User-ID', length=811)

In [103]:
filtered_rating = ratings_with_names[ratings_with_names['User-ID'].isin(top_readers)]
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0.0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1030883,275970,1880837927,0.0,The Theology of the Hammer,Millard Fuller,1994,Smyth &amp; Helwys Publishing,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...,http://images.amazon.com/images/P/1880837927.0...
1030884,275970,188717897X,0.0,The Ordeal of Integration: Progress and Resent...,Orlando Patterson,1998,Civitas Book Publisher,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...,http://images.amazon.com/images/P/188717897X.0...
1030885,275970,1888889047,0.0,Pushcart's Complete Rotten Reviews &amp; Rejec...,Bill Henderson,1998,Pushcart Press,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...,http://images.amazon.com/images/P/1888889047.0...
1030886,275970,1931868123,0.0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1030887,275970,3411086211,10.0,Die Biene.,Sybil GrÃƒ?Ã‚Â¤fin SchÃƒ?Ã‚Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...

In [107]:
y = filtered_rating.groupby("Book-Title").count()["Book-Rating"]>=50
famous_books = y[y].index
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [112]:
final_rating = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]
final_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0.0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0.0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10.0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10.0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6.0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10.0,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0.0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0.0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0.0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9.0,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [117]:
pt = final_rating.pivot_table(index='Book-Title', columns ='User-ID', values = 'Book-Rating')
pt.fillna(0, inplace= True)
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [119]:
from sklearn.metrics.pairwise import cosine_similarity

In [121]:
similarity_score = cosine_similarity(pt)

In [124]:
similarity_score

array([[1.        , 0.10255025, 0.01220856, ..., 0.12110367, 0.07347567,
        0.04316046],
       [0.10255025, 1.        , 0.2364573 , ..., 0.07446129, 0.16773875,
        0.14263397],
       [0.01220856, 0.2364573 , 1.        , ..., 0.04558758, 0.04938579,
        0.10796119],
       ...,
       [0.12110367, 0.07446129, 0.04558758, ..., 1.        , 0.07085128,
        0.0196177 ],
       [0.07347567, 0.16773875, 0.04938579, ..., 0.07085128, 1.        ,
        0.10602962],
       [0.04316046, 0.14263397, 0.10796119, ..., 0.0196177 , 0.10602962,
        1.        ]])

In [140]:
def recommend(book_name):
    #fetch index
    index = np.where(pt.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])), key = lambda x:x[1], reverse = True)[1:6]
    
    for i in similar_items:
        print(pt.index[i[0]])

In [141]:
recommend('The Notebook')

A Walk to Remember
The Rescue
One Door Away from Heaven
Toxin
The Five People You Meet in Heaven